image: alpine:3.17

stages: # List of stages for jobs, and their order of execution
  - test
  - sonarCheck
  - format
  - build

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/code/.sonar"
  GIT_DEPTH: "0"

.before_script_template:
  before_script:
    - apk add --update maven

java-sonarqube-check:
  extends: .before_script_template
  stage: sonarCheck
  script:
    - echo Running sonar analysis of the Raspberry code for ${SONAR_PROJECT_KEY}
    - sonar-scanner -Dsonar.sources=tempera-accesspoint/tempera -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.projectName="${CI_PROJECT_NAME} python ${GITLAB_USER_NAME}" -Dsonar.python.version=3.11.8
    - cd tempera-server
    - echo Running sonar analysis for ${SONAR_PROJECT_KEY}
    - mvn -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.projectName="${CI_PROJECT_NAME} java ${GITLAB_USER_NAME}" --fail-at-end verify sonar:sonar
    - cd ..
    - echo Running sonar analysis of the front end code for ${SONAR_PROJECT_KEY}
    - sonar-scanner -Dsonar.sources=tempera-server/webapp -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.projectName="${CI_PROJECT_NAME} angular ${GITLAB_USER_NAME}"
  allow_failure: true

